"""change transfers datatime type

Revision ID: 94f4e399bec6
Revises: a950d389c7ef
Create Date: 2021-08-17 10:32:07.721430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f4e399bec6'
down_revision = 'a950d389c7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_transfers', 'intime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_transfers', 'intime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
