"""change type dischttime

Revision ID: a4e45aab8842
Revises: 70eb8a908318
Create Date: 2021-08-17 09:40:17.225050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e45aab8842'
down_revision = '70eb8a908318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_admission', 'dischtime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_admission', 'dischtime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
