""" create core_transfer

Revision ID: a950d389c7ef
Revises: db7832828a90
Create Date: 2021-08-17 10:24:46.538681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a950d389c7ef'
down_revision = 'db7832828a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_transfers',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hadm_id', sa.Integer(), nullable=True),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('eventtype', sa.String(), nullable=True),
    sa.Column('careunit', sa.String(), nullable=True),
    sa.Column('intime', sa.String(), nullable=True),
    sa.Column('outtime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_core_transfers_subject_id'), 'core_transfers', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_transfers_subject_id'), table_name='core_transfers')
    op.drop_table('core_transfers')
    # ### end Alembic commands ###
