"""create core_patients relation

Revision ID: db7832828a90
Revises: a4e45aab8842
Create Date: 2021-08-17 10:03:17.084432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7832828a90'
down_revision = 'a4e45aab8842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_patients',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('anchor_age', sa.Integer(), nullable=True),
    sa.Column('anchor_year', sa.Integer(), nullable=True),
    sa.Column('anchor_year_group', sa.String(), nullable=True),
    sa.Column('dod', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.alter_column('core_admission', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('core_admission', 'hadm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_core_admission_hadm_id', table_name='core_admission')
    op.create_index(op.f('ix_core_admission_subject_id'), 'core_admission', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_admission_subject_id'), table_name='core_admission')
    op.create_index('ix_core_admission_hadm_id', 'core_admission', ['hadm_id'], unique=False)
    op.alter_column('core_admission', 'hadm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('core_admission', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_table('core_patients')
    # ### end Alembic commands ###
