"""change type to float

Revision ID: eb202c5f3e26
Revises: 94f4e399bec6
Create Date: 2021-08-17 10:45:52.349435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb202c5f3e26'
down_revision = 'db7832828a90'

#94f4e399bec6
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
